// apps/Chatbot/ReactReduxTs/src/components/Inspector/LinkInspector.tsx
import React, { ChangeEvent, ReactElement, useCallback, useState } from 'react';
import { shapes } from '@clientio/rappid';

import { useBaseInspector } from 'src/components/Inspector/useBaseInspector';
import Input from 'src/components/Input/Input';

interface Props {
    cell: shapes.app.Link;
}

const cellProps = {
    label: ['labels', 0, 'attrs', 'labelText', 'text']
};

const LinkInspector = (props: Props): ReactElement => {

    const { cell } = props;

    const [label, setLabel] = useState<string>('');

    const assignFormFields = useCallback((): void => {
        setLabel(cell.prop(cellProps.label));
    }, [cell]);

    const changeCellProp = useBaseInspector({ cell, assignFormFields });

    return (
        <>
            <h1>Component</h1>

            <label>Label
                <Input type="text"
                       placeholder="Enter label"
                       value={label}
                       onChange={(e: ChangeEvent<HTMLInputElement>) => changeCellProp(cellProps.label, e.target.value)}
                />
            </label>
        </>
    );
};

export default LinkInspector;

// apps/Chatbot/VueTs/src/components/inspector/link-inspector/link-inspector.vue
<template>
    <div>
        <h1>Link</h1>

        <label>Label
            <input type="text"
                   placeholder="Enter label"
                   v-batch
                   v-model="label"
                   @input="changeCellProp(props.label, label)">
        </label>
    </div>
</template>

<script lang="ts">
    import Component from 'vue-class-component';
    import { BaseInspector } from 'src/components/inspector/base-inspector/base-inspector';

    @Component({})
    export default class LinkInspector extends BaseInspector {

        public label: string = '';

        public props = {
            label: ['labels', 0, 'attrs', 'labelText', 'text']
        }

        protected assignFormFields(): void {
            const { cell, props } = this;
            this.label = cell.prop(props.label);
        }
    }
</script>
