// apps/Chatbot/VueTs/src/components/inspector/link-inspector/link-inspector.vue
<template>
    <div>
        <h1>Link</h1>

        <label>Label
            <input type="text"
                   placeholder="Enter label"
                   v-batch
                   v-model="label"
                   @input="changeCellProp(props.label, label)">
        </label>
    </div>
</template>

<script lang="ts">
    import Component from 'vue-class-component';
    import { BaseInspector } from 'src/components/inspector/base-inspector/base-inspector';

    @Component({})
    export default class LinkInspector extends BaseInspector {

        public label: string = '';

        public props = {
            label: ['labels', 0, 'attrs', 'labelText', 'text']
        }

        protected assignFormFields(): void {
            const { cell, props } = this;
            this.label = cell.prop(props.label);
        }
    }
</script>

// apps/Chatbot/Angular9/src/app/inspector/link-inspector/link-inspector.component.ts
/*! Rappid v3.2.0 - HTML5 Diagramming Framework - TRIAL VERSION

Copyright (c) 2015 client IO

 2020-07-25 


This Source Code Form is subject to the terms of the Rappid Trial License
, v. 2.0. If a copy of the Rappid License was not distributed with this
file, You can obtain one at http://jointjs.com/license/rappid_v2.txt
 or from the Rappid archive as was distributed by client IO. See the LICENSE file.*/


import { Component, Input } from '@angular/core';
import { shapes } from '@clientio/rappid';

import { BaseInspectorComponent } from 'src/app/inspector/base-inspector/base-inspector.component';

@Component({
    selector: 'app-link-inspector',
    templateUrl: './link-inspector.component.html',
    styleUrls: ['../inspector.component.scss']
})
export class LinkInspectorComponent extends BaseInspectorComponent {

    @Input() cell: shapes.app.Link;

    public label: string;

    public props = {
        label: ['labels', 0, 'attrs', 'labelText', 'text']
    };

    protected assignFormFields(): void {
        const { cell, props } = this;
        this.label = cell.prop(props.label);
    }
}

<ng-container>
    <h1>Link</h1>

    <label>Label
        <input type="text"
               batch
               placeholder="Enter label"
               [(ngModel)]="label"
               (ngModelChange)="changeCellProp(props.label, label)">
    </label>
</ng-container>
